version: '3.7'

networks:
    books:
        name: books-external

services:
    express-gateway:
        build:
            context: ../..
            dockerfile: ./docker/development/Dockerfile
        networks:
            - books
        volumes:
            - ../..:/app
        working_dir: /app
        ports:
            - 8000:8000
            - 9876:9876
        command: './tools/run-gateway.sh'
